// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZvSfk5jG90AQNcd3n_Rc7mbLcec_4Nyw',
    appId: '1:985769316982:web:d681c32e05031701b24557',
    messagingSenderId: '985769316982',
    projectId: 'vidassistant',
    authDomain: 'vidassistant.firebaseapp.com',
    storageBucket: 'vidassistant.firebasestorage.app',
    measurementId: 'G-41QCB6T0J8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7oC--VtYrX2qUBukEHyK-jeVRjVIRt5Y',
    appId: '1:985769316982:android:7ca35b0a04ca1fcbb24557',
    messagingSenderId: '985769316982',
    projectId: 'vidassistant',
    storageBucket: 'vidassistant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAohRcv77HfD1KJLdoi4jw2DuwJnD5wt9g',
    appId: '1:985769316982:ios:50b8dbea298f0f8fb24557',
    messagingSenderId: '985769316982',
    projectId: 'vidassistant',
    storageBucket: 'vidassistant.firebasestorage.app',
    iosBundleId: 'com.example.youtubeExtracter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAohRcv77HfD1KJLdoi4jw2DuwJnD5wt9g',
    appId: '1:985769316982:ios:50b8dbea298f0f8fb24557',
    messagingSenderId: '985769316982',
    projectId: 'vidassistant',
    storageBucket: 'vidassistant.firebasestorage.app',
    iosBundleId: 'com.example.youtubeExtracter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZvSfk5jG90AQNcd3n_Rc7mbLcec_4Nyw',
    appId: '1:985769316982:web:539b8ff5117966b3b24557',
    messagingSenderId: '985769316982',
    projectId: 'vidassistant',
    authDomain: 'vidassistant.firebaseapp.com',
    storageBucket: 'vidassistant.firebasestorage.app',
    measurementId: 'G-LGB514EQQM',
  );
}
